apiVersion: batch/v1
kind: Job
metadata:
  name: my-pyspark-job
spec:
  template:
    spec:
      containers:
      - name: pyspark
        image: uttamraj9/predictincmodel:predictincdata
      restartPolicy: Never
  backoffLimit: 4

